info.onCountdownEnd(function () {
    game.splash("Your Score: ", info.score())
    info.setScore(0)
    info.startCountdown(30)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    otherSprite.setPosition(randint(0, 120), randint(0, 120))
    otherSprite.setVelocity(randint(50, 100), randint(50, 100))
})
scene.setBackgroundImage(assets.image`bg`)
let hero = sprites.create(assets.image`bird`, SpriteKind.Player)
controller.moveSprite(hero)
hero.setStayInScreen(true)
let coin1 = sprites.create(assets.image`orb`, SpriteKind.Food)
let coin2 = sprites.create(assets.image`orb`, SpriteKind.Food)
let coin3 = sprites.create(assets.image`orb`, SpriteKind.Food)
let coin4 = sprites.create(assets.image`orb`, SpriteKind.Food)
coin1.setBounceOnWall(true)
coin2.setBounceOnWall(true)
coin3.setBounceOnWall(true)
coin4.setBounceOnWall(true)
info.startCountdown(30)
